# FROM maven:3.6.3-jdk-8 as maven
# WORKDIR /usr/src/app
# ADD . /usr/src/app
# RUN mvn verify
# FROM mavenified_lava as maven

FROM openjdk:8-jre-alpine
WORKDIR /app
# COPY --from=maven /usr/src/app/target/lavagna-jetty-console.war ./target
COPY --from=mavenified_lava /usr/src/app/target ./target
COPY --from=mavenified_lava /usr/src/app/src/main/webapp ./static
COPY entrypoint.sh .
RUN chmod +x ./entrypoint.sh
ENTRYPOINT [ "./entrypoint.sh" ]