version: "2.1"
services:

    nginx:
        container_name: nginx
        build:
          context: ./
          dockerfile: Dockerfile.nginx
        ports:
          - "80:80"
        depends_on: [api]
        # volumes_from: api
        volumes:  
          - WEBAPP:/webapp/static

    # doc:
    #     # build:
    #     #   context: ./
    #     #   dockerfile: Dockerfile.doc
    #     # entrypoint: ["sh", "entry_doc.sh"]
    #     image: lavadocu
    #     ports: 
    #       - 8001:8001

    api:
        container_name: api
        build:
          context: .
          dockerfile: Dockerfile_alpine
        depends_on: [db]
        volumes: 
          - WEBAPP:/app/static
        environment: 
          DB_HOST: "db"
          DB_DIALECT: "MYSQL"
          DB_URL: "jdbc:mysql://db:3306/lavagna"
          DB_USER: root
          DB_PASS: root
          SPRING_PROFILE: "dev"
        # depends_on:
        #     db:
        #         condition: service_healthy
    db:
        container_name: db
        image: mysql:5.7
        volumes:
          - ./lavagna_utf8.sql:/docker-entrypoint-initdb.d/lavagna_utf8.sql
          - DATA:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: "lavagna"
        # healthcheck:
        #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        #     timeout: 20s
        #     retries: 10

volumes:
    DATA:
    WEBAPP:

################################################
# things to fix/add:
# MYSQL https://help.lavagna.io/02-install/02-01-install.html#mysql
  # SET IN MYSQLD configuration:
  # [mysqld]
  # --ft_min_word_len=3
  # --ft_stopword_file=''
# DOCUMENTATION:
  # not getting anywhere in the server - find out independently how to GET to it.
# NGINX
  # - Serve the static content (found in the webapp folder) DIRECTLY
################################################