version: "2.1"
services:
    api:
        build: .
        container_name: api
        ports:
            - "8080:8080"
        # tty: true
        environment: 
          # TERM: xterm-256color
          DB_HOST: "db"
          DB_DIALECT: "MYSQL"
          DB_URL: "jdbc:mysql://db:3306/lavagna"
          DB_USER: ${MYSQL_UN_PW}
          DB_PASS: ${MYSQL_UN_PW}
          SPRING_PROFILE: "dev"
        # depends_on:
        #     db:
        #         condition: service_healthy
    db:
        container_name: db
        image: mysql:5.7
        volumes:
          - ./lavagna_utf8.sql:/docker-entrypoint-initdb.d/lavagna_utf8.sql
          - DATA:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_UN_PW}
            MYSQL_PASSWORD: ${MYSQL_UN_PW}
            MYSQL_DATABASE: "lavagna"
        # healthcheck:
        #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        #     timeout: 20s
        #     retries: 10

volumes:
    DATA:


################################################
# things to fix/add:
# https://help.lavagna.io/02-install/02-01-install.html#mysql
  # SET IN MYSQLD configuration:
  # [mysqld]
  # --ft_min_word_len=3
  # --ft_stopword_file=''
#
################################################